---
# tasks file for epel-release setup
- name: Install epel-release
  yum:
    pkg: epel-release
    state: installed

- name: Install bind-utils nginx
  yum:
    name:
      - bind-utils
      - nginx
      - python-dns

- name: Starting nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Add 80 port access
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Set hostname
  hostname:
    name: "{{ host_name_fqdn }}"

- name: Set hostname fact
  set_fact:
    ansible_fqdn: "{{ host_name_fqdn }}"

- name: Add dns-master to resolv.conf
  lineinfile: 
    dest: /etc/resolv.conf
    state: present
    line: 'nameserver {{ dns_master_ip }}'
    insertbefore: BOF

- name: Copy master key file
  copy:
    src: /root/ansible_tmp/{{domain}}_vault.key
    dest: /root/{{domain}}_vault.key
    owner: root
    group: root
    mode: 0600

- name: Copy master private file
  copy:
    src: /root/ansible_tmp/{{domain}}_vault.private
    dest: /root/{{domain}}_vault.private
    owner: root
    group: root
    mode: 0600

- name: Get master private key from file
  shell: cat /root/{{domain}}_vault.key | awk ' {print $7,$8} '
  register: master_private_key

- name: Update zones mkdev
  nsupdate:
    key_name: "{{domain}}"
    key_secret: "{{master_private_key.stdout}}"
    server: "{{dns_master_ip}}"
    zone: "{{domain}}"
    record: "{{host_name}}"
    value: "{{ ansible_default_ipv4.address }}"

- name: Update zones PTR mkdev
  nsupdate:
    key_name: "{{domain}}"
    key_secret: "{{master_private_key.stdout}}"
    server: "{{dns_master_ip}}"
    zone: "{{rev_domain}}"
    record: "{{ ansible_default_ipv4.address | ipaddr('revdns') }}"
    value: "{{ host_name }}"
    type: "PTR"
