---
- hosts: localhost
  sudo: yes

  tasks:
    - name: Add dns-master to resolv.conf
      lineinfile:
        dest: /etc/resolv.conf
        state: present
        line: 'nameserver {{ dns_master_ip }}'
        insertbefore: BOF

